/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IKPL2Guardian, IKPL2GuardianInterface } from "../IKPL2Guardian";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "attributeSet",
        type: "uint256",
      },
    ],
    name: "awakenTribe",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IKPL2Guardian__factory {
  static readonly abi = _abi;
  static createInterface(): IKPL2GuardianInterface {
    return new utils.Interface(_abi) as IKPL2GuardianInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IKPL2Guardian {
    return new Contract(address, _abi, signerOrProvider) as IKPL2Guardian;
  }
}
