/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "LinkTokenInterface",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.LinkTokenInterface__factory>;
    getContractFactory(
      name: "VRFConsumerBase",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.VRFConsumerBase__factory>;
    getContractFactory(
      name: "AccessControl",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AccessControl__factory>;
    getContractFactory(
      name: "IAccessControl",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IAccessControl__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "ERC721",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC721__factory>;
    getContractFactory(
      name: "ERC721Enumerable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC721Enumerable__factory>;
    getContractFactory(
      name: "ERC721URIStorage",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC721URIStorage__factory>;
    getContractFactory(
      name: "IERC721Enumerable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721Enumerable__factory>;
    getContractFactory(
      name: "IERC721Metadata",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721Metadata__factory>;
    getContractFactory(
      name: "IERC721",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721__factory>;
    getContractFactory(
      name: "IERC721Receiver",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721Receiver__factory>;
    getContractFactory(
      name: "ERC165",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC165__factory>;
    getContractFactory(
      name: "IERC165",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC165__factory>;
    getContractFactory(
      name: "FxERC1155ChildTunnel",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.FxERC1155ChildTunnel__factory>;
    getContractFactory(
      name: "FxERC1155RootTunnel",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.FxERC1155RootTunnel__factory>;
    getContractFactory(
      name: "FxERC20ChildTunnel",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.FxERC20ChildTunnel__factory>;
    getContractFactory(
      name: "FxERC20RootTunnel",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.FxERC20RootTunnel__factory>;
    getContractFactory(
      name: "FxERC721ChildTunnel",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.FxERC721ChildTunnel__factory>;
    getContractFactory(
      name: "FxERC721RootTunnel",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.FxERC721RootTunnel__factory>;
    getContractFactory(
      name: "FxMintableERC20ChildTunnel",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.FxMintableERC20ChildTunnel__factory>;
    getContractFactory(
      name: "FxMintableERC20RootTunnel",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.FxMintableERC20RootTunnel__factory>;
    getContractFactory(
      name: "FxStateChildTunnel",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.FxStateChildTunnel__factory>;
    getContractFactory(
      name: "FxStateRootTunnel",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.FxStateRootTunnel__factory>;
    getContractFactory(
      name: "FxChild",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.FxChild__factory>;
    getContractFactory(
      name: "IFxMessageProcessor",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IFxMessageProcessor__factory>;
    getContractFactory(
      name: "IStateReceiver",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IStateReceiver__factory>;
    getContractFactory(
      name: "FxRoot",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.FxRoot__factory>;
    getContractFactory(
      name: "IFxStateSender",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IFxStateSender__factory>;
    getContractFactory(
      name: "IStateSender",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IStateSender__factory>;
    getContractFactory(
      name: "FxERC721ChildTunnel",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.FxERC721ChildTunnel__factory>;
    getContractFactory(
      name: "FxERC721RootTunnel",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.FxERC721RootTunnel__factory>;
    getContractFactory(
      name: "IKPGuardian",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IKPGuardian__factory>;
    getContractFactory(
      name: "KPL1FxTunnel",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.KPL1FxTunnel__factory>;
    getContractFactory(
      name: "KPL1GuardianNFT",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.KPL1GuardianNFT__factory>;
    getContractFactory(
      name: "IKPL2Guardian",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IKPL2Guardian__factory>;
    getContractFactory(
      name: "KPL2AFxTunnel",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.KPL2AFxTunnel__factory>;
    getContractFactory(
      name: "KPL2AGuardianNFT",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.KPL2AGuardianNFT__factory>;
    getContractFactory(
      name: "Create2",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Create2__factory>;
    getContractFactory(
      name: "ERC1155",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC1155__factory>;
    getContractFactory(
      name: "ERC1155Holder",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC1155Holder__factory>;
    getContractFactory(
      name: "ERC1155Receiver",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC1155Receiver__factory>;
    getContractFactory(
      name: "ERC165",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC165__factory>;
    getContractFactory(
      name: "ERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC20__factory>;
    getContractFactory(
      name: "ERC721",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC721__factory>;
    getContractFactory(
      name: "IERC1155",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC1155__factory>;
    getContractFactory(
      name: "IERC1155MetadataURI",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC1155MetadataURI__factory>;
    getContractFactory(
      name: "IERC1155Receiver",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC1155Receiver__factory>;
    getContractFactory(
      name: "IERC165",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC165__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "IERC721",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721__factory>;
    getContractFactory(
      name: "IERC721Metadata",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721Metadata__factory>;
    getContractFactory(
      name: "IERC721Receiver",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721Receiver__factory>;
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "FxERC1155",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.FxERC1155__factory>;
    getContractFactory(
      name: "FxERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.FxERC20__factory>;
    getContractFactory(
      name: "FxERC721",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.FxERC721__factory>;
    getContractFactory(
      name: "IFxERC1155",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IFxERC1155__factory>;
    getContractFactory(
      name: "IFxERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IFxERC20__factory>;
    getContractFactory(
      name: "IFxERC721",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IFxERC721__factory>;
    getContractFactory(
      name: "FxBaseChildTunnel",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.FxBaseChildTunnel__factory>;
    getContractFactory(
      name: "IFxMessageProcessor",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IFxMessageProcessor__factory>;
    getContractFactory(
      name: "FxBaseRootTunnel",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.FxBaseRootTunnel__factory>;
    getContractFactory(
      name: "ICheckpointManager",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ICheckpointManager__factory>;
    getContractFactory(
      name: "IFxStateSender",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IFxStateSender__factory>;

    getContractAt(
      name: "LinkTokenInterface",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.LinkTokenInterface>;
    getContractAt(
      name: "VRFConsumerBase",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.VRFConsumerBase>;
    getContractAt(
      name: "AccessControl",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.AccessControl>;
    getContractAt(
      name: "IAccessControl",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IAccessControl>;
    getContractAt(
      name: "IERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "ERC721",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC721>;
    getContractAt(
      name: "ERC721Enumerable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC721Enumerable>;
    getContractAt(
      name: "ERC721URIStorage",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC721URIStorage>;
    getContractAt(
      name: "IERC721Enumerable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721Enumerable>;
    getContractAt(
      name: "IERC721Metadata",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721Metadata>;
    getContractAt(
      name: "IERC721",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721>;
    getContractAt(
      name: "IERC721Receiver",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721Receiver>;
    getContractAt(
      name: "ERC165",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC165>;
    getContractAt(
      name: "IERC165",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC165>;
    getContractAt(
      name: "FxERC1155ChildTunnel",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.FxERC1155ChildTunnel>;
    getContractAt(
      name: "FxERC1155RootTunnel",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.FxERC1155RootTunnel>;
    getContractAt(
      name: "FxERC20ChildTunnel",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.FxERC20ChildTunnel>;
    getContractAt(
      name: "FxERC20RootTunnel",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.FxERC20RootTunnel>;
    getContractAt(
      name: "FxERC721ChildTunnel",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.FxERC721ChildTunnel>;
    getContractAt(
      name: "FxERC721RootTunnel",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.FxERC721RootTunnel>;
    getContractAt(
      name: "FxMintableERC20ChildTunnel",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.FxMintableERC20ChildTunnel>;
    getContractAt(
      name: "FxMintableERC20RootTunnel",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.FxMintableERC20RootTunnel>;
    getContractAt(
      name: "FxStateChildTunnel",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.FxStateChildTunnel>;
    getContractAt(
      name: "FxStateRootTunnel",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.FxStateRootTunnel>;
    getContractAt(
      name: "FxChild",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.FxChild>;
    getContractAt(
      name: "IFxMessageProcessor",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IFxMessageProcessor>;
    getContractAt(
      name: "IStateReceiver",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IStateReceiver>;
    getContractAt(
      name: "FxRoot",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.FxRoot>;
    getContractAt(
      name: "IFxStateSender",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IFxStateSender>;
    getContractAt(
      name: "IStateSender",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IStateSender>;
    getContractAt(
      name: "FxERC721ChildTunnel",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.FxERC721ChildTunnel>;
    getContractAt(
      name: "FxERC721RootTunnel",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.FxERC721RootTunnel>;
    getContractAt(
      name: "IKPGuardian",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IKPGuardian>;
    getContractAt(
      name: "KPL1FxTunnel",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.KPL1FxTunnel>;
    getContractAt(
      name: "KPL1GuardianNFT",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.KPL1GuardianNFT>;
    getContractAt(
      name: "IKPL2Guardian",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IKPL2Guardian>;
    getContractAt(
      name: "KPL2AFxTunnel",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.KPL2AFxTunnel>;
    getContractAt(
      name: "KPL2AGuardianNFT",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.KPL2AGuardianNFT>;
    getContractAt(
      name: "Create2",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Create2>;
    getContractAt(
      name: "ERC1155",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC1155>;
    getContractAt(
      name: "ERC1155Holder",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC1155Holder>;
    getContractAt(
      name: "ERC1155Receiver",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC1155Receiver>;
    getContractAt(
      name: "ERC165",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC165>;
    getContractAt(
      name: "ERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC20>;
    getContractAt(
      name: "ERC721",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC721>;
    getContractAt(
      name: "IERC1155",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC1155>;
    getContractAt(
      name: "IERC1155MetadataURI",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC1155MetadataURI>;
    getContractAt(
      name: "IERC1155Receiver",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC1155Receiver>;
    getContractAt(
      name: "IERC165",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC165>;
    getContractAt(
      name: "IERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "IERC721",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721>;
    getContractAt(
      name: "IERC721Metadata",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721Metadata>;
    getContractAt(
      name: "IERC721Receiver",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721Receiver>;
    getContractAt(
      name: "Ownable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;
    getContractAt(
      name: "FxERC1155",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.FxERC1155>;
    getContractAt(
      name: "FxERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.FxERC20>;
    getContractAt(
      name: "FxERC721",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.FxERC721>;
    getContractAt(
      name: "IFxERC1155",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IFxERC1155>;
    getContractAt(
      name: "IFxERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IFxERC20>;
    getContractAt(
      name: "IFxERC721",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IFxERC721>;
    getContractAt(
      name: "FxBaseChildTunnel",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.FxBaseChildTunnel>;
    getContractAt(
      name: "IFxMessageProcessor",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IFxMessageProcessor>;
    getContractAt(
      name: "FxBaseRootTunnel",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.FxBaseRootTunnel>;
    getContractAt(
      name: "ICheckpointManager",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ICheckpointManager>;
    getContractAt(
      name: "IFxStateSender",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IFxStateSender>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
